# Default Profile Configuration
spring:
  application:
    name: user-management-api

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # Use 'create-drop' for development, 'validate' for production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  level:
    com.enterprise.user_management: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    disable-swagger-default-url: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# JWT Configuration
jwt:
  secret: heheBoiiiSecurityTokenButMuchLongerCauseChotoKajKoreNa
  expiration: 86400000

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/user_management_db

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    com.enterprise.user_management: DEBUG

jwt:
  secret: heheBoiiDevTokenButMuchLongerCauseChotoKajKoreNa
  expiration: 3600000

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_management_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false  # Disable Swagger in production for security

logging:
  level:
    com.enterprise.user_management: INFO
    org.springframework.security: WARN

jwt:
  secret: ${JWT_SECRET:heheBoiiProdTokenButMuchLongerCauseChotoKajKoreNa}
  expiration: ${JWT_EXPIRATION:86400000}

---
# Test Profile
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: heheBoiiTestProfileTokenButMuchLongerCauseChotoKajKoreNa
  expiration: 3600000